version: 2.0.{build}
image: Visual Studio 2017
configuration: Release
skip_tags: true
environment:
  FTP_SERVER:
    secure: kxKILYuyxyQkHS2b4dbqw52AzETflDBT0vUIcBFY7v8=
  FTP_USER: 
    secure: 3Kls+mo3sXTdX6tqhfVIoajt3lGjJgaNCvqFBjpiT6k=
  FTP_PASSWORD:
    secure: x2kfU56dAJmCtXvY+t3RAw==
  GITHUB_DEPLOY_TOKEN:
    secure: WGPN509P83WUoyHa9LJ+yXqS4zm8Ql1mOg9pzl3eUzg0JWEO+pjL1hJEHgclkUPR
deploy:
- provider: GitHub
  auth_token: $(GITHUB_DEPLOY_TOKEN)
  on:
    branch: H2OS_EK

- provider: FTP
  host: $(FTP_SERVER)
  protocol: ftp
  username: $(FTP_USER)
  password: $(FTP_PASSWORD)
  folder: /Tools/PC/h2codez/$(APPVEYOR_BUILD_VERSION)-$(APPVEYOR_REPO_COMMIT)
  active_mode: false
  beta: true
  debug: false
  on:
    branch: H2OS_EK
    
- provider: FTP
  host: $(FTP_SERVER)
  protocol: ftp
  username: $(FTP_USER)
  password: $(FTP_PASSWORD)
  folder: /Tools/PC/h2codez/latest
  active_mode: false
  beta: true
  debug: false
  on:
    branch: H2OS_EK
before_build:
- cmd: 'echo #define version ^"%APPVEYOR_BUILD_VERSION%-%APPVEYOR_REPO_COMMIT:~0,7%^" 1>  H2Codez\Version.h'
- cmd: 'cat H2Codez\Version.h'
build:
  verbosity: minimal
before_package:
- ps: Add-Content version $env:APPVEYOR_BUILD_VERSION -NoNewLine
- ps: Add-Content hash ((Get-FileHash "C:\Program Files (x86)\Microsoft Games\Halo 2 Map Editor\H2Codez.dll" -Algorithm MD5).Hash) -NoNewLine
- cmd: xcopy /i "C:\Program Files (x86)\Microsoft Games\Halo 2 Map Editor\H2Codez.dll" ".\Release\"
- cmd: xcopy /i "C:\Program Files (x86)\Microsoft Games\Halo 2 Map Editor\H2Codez.pdb" ".\Release\"
artifacts:
- path: '\Release\*'
- path: '\hash'
